routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController@swap');

/* ----------------------------------------------------------------------- */

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    includeRouteFiles(__DIR__.'/Frontend/');
});

/* ----------------------------------------------------------------------- */

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    includeRouteFiles(__DIR__.'/Backend/');

});

/*
 * Consultancy Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Agency', 'prefix' => 'agency', 'as' => 'agency.', 'middleware' => 'agency'], function () {
    /*
     * These routes need view-consultancy permission
     * (good if you want to allow more than one group in the consultancy,
     * then limit the consultancy features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    includeRouteFiles(__DIR__.'/Agency/');
});


/**
 * Property manager routes
 * Namespaces indicate folder structure
 */

Route::group(['namespace' => 'PropertyManager', 'prefix' => 'property-manager', 'as' => 'property-manager.', 'middleware' => 'property-manager'], function () {
    /**
     * These routes need view-property-dashboard permission
     */
    includeRouteFiles(__DIR__.'/PropertyManager/');
});

Route::group(['namespace' => 'UserDashboard', 'as' => 'user-dashboard.', 'middleware' => 'user-dashboard'], function () {
    /**
     * These routes need view-property-dashboard permission
     */
    includeRouteFiles(__DIR__.'/UserDashboard/');
});

Route::get('terms-and-conditions', function () {
    return view('frontend.termsandconditions');
});

Route::get('privacy-policy', function () {
    return view('frontend.privacypolicy');
});

Route::get('about-us', function () {
    return view('frontend.aboutus');
});

Route::get('tenant', function () {
    return view('frontend.tenant');
});

Route::get('propertymanager', function () {
    return view('frontend.propertymanager');
});

Route::get('contact-us', function () {
    return view('frontend.contactus');
});

Route::get('pdf', function () {
    return view('pdf');
});

Route::get('getting-started', function () {
    return view('frontend.getting-started');
});

Route::get('property-manager-faq', function () {
    return view('frontend.pm-faq');
});

Route::get('tenant-faq', function () {
    return view('frontend.tenant-faq');
});

Route::resource('employment-confirmation', 'EmploymentConfirmationController');

Route::resource('history-confirmation', 'HistoryConfirmationController');

Route::resource('docusign', 'API\DocusignController');

Route::get('/media/{file}','MediaServerController@serveImages')
            ->where(['file'=>'.*']);

Route::get('thank-you', function () {
    return "Thank You!";
});

app/Models/Agency.php
<?php

namespace App\Models;

use App\Models\Access\User\User;
use App\Models\Agency\MailTemplate;
use App\Models\Agency\AgencyLeaseTerm;
use Illuminate\Database\Eloquent\Model;
use App\Models\Agency\SupportingDocument;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Agency extends Model implements HasMedia
{
    use SoftDeletes;
    use HasMediaTrait;
    
    protected $fillable = [
        'name',
        'agency_id',
        'user_id',
        'address',
        'phone_number',
        'email',
        'registration_number',
        'status',
        'website',
        'suburb',
        'state',
        'post_code',
        'preferred_color'
    ];

    protected $dates = ['deleted_at'];

    CONST STATES = [
        'NSW', 'ACT', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getStateNameAttribute()
    {
        return self::STATES[$this->state];
    }

    public function leaseTerms()
    {
        return $this->hasOne(AgencyLeaseTerm::class, 'agency_id');
    }

    public function supportingDocument()
    {
        return $this->hasMany(SupportingDocument::class, 'agency_id');
    }

    public function logo()
    {
        if ($this->getFirstMedia('agency_logos')) {
            return $this->getFirstMedia('agency_logos')->getUrl();
        }
        return false;
    }

    public function mail_templates()
    {
        return $this->hasMany(MailTemplate::class, 'agency_id');
    }
}

app/Http/Controllers/Agency/PropertyManagerController.php
<?php

namespace App\Http\Controllers\Agency;

use Illuminate\Http\Request;
use App\Models\Access\User\User;
use App\Http\Controllers\Controller;
use App\Events\Frontend\Auth\UserRegistered;
use App\Notifications\Frontend\Auth\UserNeedsConfirmation;

use Illuminate\Support\Facades\Mail;
use App\Mail\UserNeedsConfirmationMail;
use App\Mail\PropertyManagerCreatedMail;

class PropertyManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('agency_id', auth()->user()->agency_id)->whereHas('roles', function($q){
                    $q->where('name', 'property-manager');
                })->get();

        return view('agency.property-manager.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('agency.property-manager.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required', 
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',

        ]);
        $user = User::create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'status' => '1',
            'confirmed' => '1',
            'created_by_id' => auth()->user()->id,
            'agency_id' => auth()->user()->agency->id,
        ]);


        flash('Property Manager Created Successfully.')->success();

        event(new UserRegistered($user));
        
        Mail::to($user->email)->send(new PropertyManagerCreatedMail);
        
        // $user->notify(new UserNeedsConfirmation($user->confirmation_code));
        // Mail::to($user->email)->send(new UserNeedsConfirmationMail($user->confirmation_code));
        
        $user->attachRole(3);

        return redirect()->route('agency.property-managers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('agency.property-manager.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required', 
            'email' => 'required|string|email|max:255|unique:users,email,'.$id,
        ]);

        $user = User::find($id);
        
        if ($request->password) {
            $this->validate($request, [
                'password' => 'string|min:6|confirmed',
            ]);

            $user->update([
                'password' => bcrypt($request->password)
            ]);
        }

        $user = User::find($id)->update([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'email' => $request->email,
        ]);


        flash('Property Manager Successfully Updated.')->success();

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = user::find($id)->delete();

        flash('Property manager deleted successfully');

        return redirect()->back()->withFlashSuccess('Property manager deleted successfully');
    }
        public function delete()
    {
         user::find(request('id'))->delete();


        flash('Property manager deleted successfully');

        return response()->json([], 200);
    }
}

app/Http/Controllers/Backend/Report/BondsureController.php
<?php

namespace App\Http\Controllers\Backend\Report;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Tenant\TenantApplication;
use App\Models\BondRequest;

class BondsureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
            //$applications = TenantApplication::where('bond_assistance', 'yes')->get();

            $applications = BondRequest::latest()->get();
            
      
        return view('backend.report.bondsure.index', compact('applications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/UserManagement/PropertyManagerController.php
<?php

namespace App\Http\Controllers\Backend\UserManagement;

use Illuminate\Http\Request;
use App\Models\Access\User\User;
use App\Http\Controllers\Controller;

class PropertyManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $propertyManagers = User::whereHas('roles', function($q){
            $q->where('name', 'property-manager');
        })->get();
       return view('backend.user.property-manager.index', compact('propertyManagers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function agencyconfirm()
    { 

        User::find(request('id'))->update(['confirmed' => '1']);
        
        return redirect()->back()->withFlashSuccess('Agency has been confirmed');
        //$this->consultancy->delete($consultancy);

        //return redirect()->route('admin.consultancy.index')->withFlashSuccess(trans('alerts.backend.consultancy.deleted'));
    }
}

app/Http/Controllers/PropertyManager/ConnectionServiceController.php
<?php

namespace App\Http\Controllers\PropertyManager;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Tenant\TenantApplication;
use App\Models\Application\ApplicationMovingService;

class ConnectionServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $applications = TenantApplication::applicationForAgency()
            ->applicationForPropertyManager()
            ->filterByStatus(request('status'))
            ->search(request('search'))
            ->get();

        // $connectionServices = ApplicationMovingService::latest()->get();

        return view('property-manager.connection-service.index', compact('applications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PropertyManager/DashboardController.php
<?php

namespace App\Http\Controllers\PropertyManager;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Tenant\TenantApplication;

class DashboardController extends Controller
{
    public function index()
    {
        if (auth()->user()->hasRole('agency-admin')) {
            $inbox = TenantApplication::applicationForAgency()
            ->count();

            $accepted = TenantApplication::applicationForAgency()
            ->whereStatus(2)
            ->count();

            $approved = TenantApplication::applicationForAgency()
            ->whereStatus(3)
            ->count();
        } else {
            $inbox = TenantApplication::applicationForPropertyManager()->count();

            $accepted = TenantApplication::applicationForPropertyManager()
            ->whereStatus(2)
            ->count();

            $approved = TenantApplication::applicationForPropertyManager()
            ->whereStatus(3)
            ->count();
        }

        return view('property-manager.dashboard', compact(
          'inbox',
          'accepted',
          'approved'
      ));
    }
}

resources/views/property-manager/bondsure/create.blade.php
@extends('property-manager.layouts.app')

@section('page-header')
<h1 class="page-title">
    {{ app_name() }}
    <small>{{ trans('strings.property-manager.dashboard.title') }}</small>
</h1>
@endsection

@section('content')
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            {{-- <div class="page-title">
                <h1>Bond Request</h1>
            </div> --}}
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="{{ route('property-manager.dashboard') }}"><b>Dashboard</b></a></li>
                    <li><a href="{{ route('property-manager.bond-requests.index') }}"><b>Bond Request</b></a></li>
                    <li class="active">Create</li>
                </ol>
            </div>
        </div>
    </div>
</div>

@include('flash::message')

<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <strong>Bond Request</strong>
        </div>
        {{ Form::open(['class' => 'form-horizontal', 'method' => 'post', 'route' => 'property-manager.bond-requests.store', 'enctype' => 'multipart/form-data', 'id' => 'apply-prop-form']) }}
        <div class="card-body card-block">
            @include('property-manager.bondsure._form')
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary btn-sm pull-right">
                Submit
            </button>
            <button type="reset" class="btn btn-danger btn-sm">
                Reset
            </button>
        </div>
        {{ Form::close() }}
    </div>
</div>

@endsection

@section ('after-scripts')
<script type="text/javascript">
    CKEDITOR.replace('bond-requests-body');
    
    jQuery( "#ongoing-payment-datepicker" ).datepicker({ dateFormat: 'dd/mm/yy', changeYear:true, yearRange: "{{ config('tenancy-application.year-range') }}" }).val();

    // form validation
    jQuery('#apply-prop-form').validate({
        errorClass: 'error-message',
        rules : {
            // Property Details
            tenant_code : 'required',
            title : 'required',
            first_name : 'required',
            last_name: 'required',
            address: 'required',
            suburb: 'required',
            state : 'required',
            postcode: 'required',
            payment_amount: { required: true, number: true},
            mobile_number: { required: true, number: true},
            phone_number: { number: true},
            email : 'required',
            subject: 'required',
            body: 'required',
        }
    });

</script>
@endsection

resources/views/property-manager/bondsure/default-template.blade.php
<p>Dear Applicant,  &nbsp;</p>

<p>
	Your Tenancy Application has been Approved for address: &nbsp;.<br />
	&nbsp;
</p>
<p>Please Click PAY NOW button below to pay your bond deposit.</p>

<p>If you need bond assistance, then we can help you with EasyBondPay</p>

[[EasyBondPayLogo]]

<p>Please click on the EasyBondPay button below to assist you with Bond Payment. </p>

[[EasyBondPayButton]]

<p><br />
	{{ auth()->user()->name }}<br />
	{{ auth()->user()->email }}<br />
	@if (auth()->user()->agency_profile())
	<a href="{{ auth()->user()->agency_profile()->website }}">{{ auth()->user()->agency_profile()->website }}</a>
	@endif
</p>

resources/views/property-manager/bondsure/index-old.blade.php
@extends('property-manager.layouts.app')

@section('page-header')
<h1 class="page-title">
    {{ app_name() }}
    <small>{{ trans('strings.property-manager.dashboard.title') }}</small>
</h1>
@endsection

@section('content')
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            {{-- <div class="page-title">
                <h1>BondSure Application Requests</h1>
            </div> --}}
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                     <li><a href="{{ route('property-manager.dashboard') }} "><b>Dashboard</b></a></li>
                    <li class="active"><b>Bond Application Requests</b></li>
                </ol>
            </div>
        </div>
    </div>
</div>
@include('flash::message')
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">
                            Bond Application Requests
                             <button class="btn btn-primary btn-sm" id="download-total-application-report" style="display: none;">Download</button>
                        </strong>
                        
  
                    </div>
                    <div class="card-body">
                        {{-- <div class="row">
                        <div class="col-md-3">
                                   <div class="dropdown show">
                                    Filter by: <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                       {{ request('status') ? ucwords(request('status')) : 'Inbox' }}
                                      </a>
                                       <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" href="{{ route('property-manager.applications.index', ['status' => 'inbox']) }}">Inbox</a>
                                     
                                        @foreach (App\Models\Tenant\TenantApplication::APPLICATIONSTATUS as $status)
                                              <a class="dropdown-item" href="{{ route('property-manager.applications.index', ['status' => $status]) }}">{{ ucwords($status) }}</a>
                                         @endforeach
                                      </div>
                                    </div>              
                        </div>
                        <div class="col-md-4 offset-md-5" style="margin-bottom: 10px;">
                         {{ Form::open(['route' => 'property-manager.applications.index', 'method' => 'get']) }}
                         <div class="input-group">
                            {{ Form::text('search', request('search'), ['class' => 'form-control', 'placeholder' => 'Search']) }}
                            <div class="input-group-btn">
                                {{ Form::submit('Search', ['class' => 'btn btn-primary']) }}
                            </div>
                        </div>
                        {{ Form::close() }}
                    </div>
                </div> --}}
                <div class="table-responsive">
                    <table class="table table-bordered" id="bondsure-tenant-applications-table">
                        <thead>
                            <th>State</th>
                            <th>Tenant Name</th>
                            <th>Tenant Email</th>
                            <th>Status</th>
                            @if (request('status') == 'forwarded')
                                <th>Forwarded To</th>
                            @endif
                            <th>Date</th>
                            <th class="noExl no-sort">Action</th>
                        </thead>
                        <tbody>
                            @foreach ($applications as $application)
                            <tr>
                                <td>{{ $application->state_name }}</td>
                                <td>{{ $application->user->name }}</td>
                                <td>{{ $application->user->email }}</td>
                                <td>{{ ucwords($application->status_name) }}</td>
                                @if (request('status') == 'forwarded')
                                    <td>
                                        {{ optional($application->forwardedTo->sentBy)->name }}
                                    </td>
                                @endif
                                <td class="noExl">{{ $application->created_at->format('Y/m/d H:i') }}</td>
                                <td class="noExl">
                                    <a href="{{ route('property-manager.applications.show', $application->id) }}" class="btn btn-sm btn-info"  title="Details">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{{ route('property-manager.tenancy-pdf-application.show', $application->id) }}" class="btn btn-primary btn-sm" title="Show PDF" target="_blank">
                                        <i class="fa fa-file-pdf-o"></i>
                                    </a>
                                    <a href="{{ route('property-manager.applications.destroy', $application->id) }}" data-method="DELETE" class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                </div>
              {{--   <div class="card-footer">
                    {{ $applications->appends(request()->input())->links() }}
                </div> --}}
            </div>
        </div>
    </div>
</div>
</div>
@endsection
  
@section('after-scripts')
<link rel="stylesheet" type="text/css" href="/datatables/datatables.bootstrap.min.css">
<script src="/datatables/datatables.min.js"></script>
<script src="/datatables/datatables.bootstrap.min.js"></script>
<link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        /*jQuery('#download-total-application-report').on('click', function (){
            jQuery(".table").table2excel({
                exclude: ".noExl",
                name: "Tenancy Total Application",
                filename: "BondSure" + new Date().toISOString().replace(/[\-\:\.]/g, ""),
                fileext: ".xlsx",
                exclude_img: true,
                exclude_links: true,
            });
            console.clear();
        });*/
        jQuery('#bondsure-tenant-applications-table').DataTable({
            "columnDefs": [ {
                "targets": 'no-sort',
                "orderable": false,
            } ],
            "order": [[4, "desc"]],
            "dom": 'Blfrtip',
            "buttons": [
                { 
                  extend: 'excel',
                  text: 'Download',
                  className: 'downloadButton',
                  title: 'Tenancy Application - Bond Application Requests',
                  filename: "Bond-Application-Requests-" + new Date().toISOString().replace(/[\-\:\.]/g, ""),
                  exportOptions: {
                    //columns: [ 0, 1, 2,3,4,6 ]
                    columns: 'th:not(:last-child)'
                    }
                } 
            ]
        });
    });
</script>

@endsection