routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController@swap');

/* ----------------------------------------------------------------------- */

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    includeRouteFiles(__DIR__.'/Frontend/');
});

/* ----------------------------------------------------------------------- */

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    includeRouteFiles(__DIR__.'/Backend/');

});

/*
 * Consultancy Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Agency', 'prefix' => 'agency', 'as' => 'agency.', 'middleware' => 'agency'], function () {
    /*
     * These routes need view-consultancy permission
     * (good if you want to allow more than one group in the consultancy,
     * then limit the consultancy features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    includeRouteFiles(__DIR__.'/Agency/');
});


/**
 * Property manager routes
 * Namespaces indicate folder structure
 */

Route::group(['namespace' => 'PropertyManager', 'prefix' => 'property-manager', 'as' => 'property-manager.', 'middleware' => 'property-manager'], function () {
    /**
     * These routes need view-property-dashboard permission
     */
    includeRouteFiles(__DIR__.'/PropertyManager/');
});

Route::group(['namespace' => 'UserDashboard', 'as' => 'user-dashboard.', 'middleware' => 'user-dashboard'], function () {
    /**
     * These routes need view-property-dashboard permission
     */
    includeRouteFiles(__DIR__.'/UserDashboard/');
});

Route::get('terms-and-conditions', function () {
    return view('frontend.termsandconditions');
});

Route::get('privacy-policy', function () {
    return view('frontend.privacypolicy');
});

Route::get('about-us', function () {
    return view('frontend.aboutus');
});

Route::get('tenant', function () {
    return view('frontend.tenant');
});

Route::get('propertymanager', function () {
    return view('frontend.propertymanager');
});

Route::get('contact-us', function () {
    return view('frontend.contactus');
});

Route::get('pdf', function () {
    return view('pdf');
});

Route::get('getting-started', function () {
    return view('frontend.getting-started');
});

Route::get('property-manager-faq', function () {
    return view('frontend.pm-faq');
});

Route::get('tenant-faq', function () {
    return view('frontend.tenant-faq');
});

Route::resource('employment-confirmation', 'EmploymentConfirmationController');

Route::resource('history-confirmation', 'HistoryConfirmationController');

Route::resource('docusign', 'API\DocusignController');

Route::get('/media/{file}','MediaServerController@serveImages')
            ->where(['file'=>'.*']);

Route::get('thank-you', function () {
    return "Thank You!";
});

app/Models/BondRequest.php
<?php

namespace App\Models;

use App\Models\Access\User\User;
use Illuminate\Database\Eloquent\Model;
use App\Models\Tenant\TenantApplication;

class BondRequest extends Model
{
    protected $fillable = [
        'tenant_code',
        'title',
        'first_name',
        'last_name',
        'dob',
        'address',
        'suburb',
        'state',
        'postcode',
        'payment_amount',
        'mobile_number',
        'phone_number',
        'email',
        'subject',
        'body',
        'sent_by',
        'email_status',
        'efund_contract_link',
        'efund_contract_id',
        'finance_period'
    ];

    public function sentBy()
    {
        return $this->belongsTo(User::class, 'sent_by');
    }

    public function getNameAttribute()
    {
        return config('tenancy-application.title')[$this->title]." ".$this->first_name." ".$this->last_name;
    }

    public function getStateNameAttribute()
    {
        return $this->state || $this->state == '0' ? TenantApplication::STATES[$this->state] : null;
    }
}

app/Http/Controllers/UserDashboard/ApplicationController.php
<?php

namespace App\Http\Controllers\UserDashboard;

use PDF;
use App\Models\Agency;
use App\Models\Setting;
use Illuminate\Http\Request;
use App\Models\Access\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use App\Models\Tenant\TenantApplication;
use App\Models\Application\ApplicationPet;
use App\Mail\Application\MovingServiceMail;
use App\Models\Application\ApplicationVehicle;
use App\Models\Application\ApplicationOccupant;
use App\Models\Application\ApplicationChildren;
use App\Mail\Application\NewApplicationSubmitted;
use App\Mail\Application\InviteJointApplicant;
use App\Models\Application\ApplicationMovingService;
use App\Mail\Application\PropertyManager\NewApplicationSubmittedForPropertyManager;

// docusign
use DocuSign;
use App\API\TenancyDocuSign;
use DocuSign\eSign\Api\EnvelopesApi;
use App\Rules\UserDashboard\AgencyName;
use DocuSign\eSign\Api\EnvelopesApi\GetDocumentOptions;
use GuzzleHttp\Client;


class ApplicationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $applications = $this->application_filter();

        return view('user-dashboard.application.index', compact('applications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (auth()->user()->tenantProfile && auth()->user()->tenantProfile->status == '1') {

            //CHECK WEATHER APPLICANT IS JOINT APPLICANT THAN PREFILL PROP DETAILS
            $isJointApplicant = ApplicationOccupant::whereOccupantEmail(auth()->user()->email)
                                ->Where('occupant_as_joint_tenant',  'yes')
                                ->latest()
                                ->first();
            if($isJointApplicant){

                $jointAppAlreadySubmitted = TenantApplication::whereJointAppId($isJointApplicant->application_id)->count();
                //echo $jointAppAlreadySubmitted;exit;
                if($jointAppAlreadySubmitted==0){
                    $primaryApplicantion = TenantApplication::whereId($isJointApplicant->application_id)
                                                            //->where('joint_app_id', '!=', $isJointApplicant->application_id)
                                                            ->latest()->first();
                    //echo '<pre>';print_r($primaryApplicantion);exit;    
                }
                
            }

            $latestApplicationExistance = TenantApplication::whereUserId(auth()->user()->id)->count() > 0;
            $latestOccupants = $latestApplicationExistance ? TenantApplication::whereUserId(auth()->user()->id)->latest()->first()->occupants : null;

            $latestChildren = $latestApplicationExistance ? TenantApplication::whereUserId(auth()->user()->id)->latest()->first()->children : null;

            $latestVehicle = $latestApplicationExistance ? TenantApplication::whereUserId(auth()->user()->id)->latest()->first()->vehicles : null;

            $latestPets = $latestApplicationExistance ? TenantApplication::whereUserId(auth()->user()->id)->latest()->first()->pets : null;

            $latestApplication = $latestApplicationExistance ? TenantApplication::whereUserId(auth()->user()->id)->latest()->first() : null;

            return view('user-dashboard.application.create', compact('relationships', 'latestOccupants', 'latestChildren', 'latestVehicle', 'latestPets', 'latestApplication', 'primaryApplicantion'));
        }
        flash('Please Complete Your Profile.')->error();
        return redirect()->route('user-dashboard.profile.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            // Property Details
            'applied_for' => 'required',
            'state' => 'required',
            'suburb' => 'required',
            'post_code' => 'required|numeric',
            'property_type' => 'required',
            'number_of_bedrooms' => 'required',
            'commencement_date' => 'required',
            'length_of_lease' => 'required',
            'weekly_rent' => 'required',
            'monthly_rent' => 'required',
            'bond' => 'required',
            //'bond_assistance' => 'required',
            'property_found_in' => 'required',

            // Property Manager Details
            'agency_name' => ['required',new AgencyName],

            'property_manager_name' => 'required',
            'property_manager_email' => 'required',

            // Occupancy Details
            'number_of_occupant' => 'required',
            'number_of_children' => 'required',
            'number_of_vehicles' => 'required',
            'number_of_pets' => 'required',

            // Agent Specific
            'is_tenant_terminated' => 'required',
            'tenant_terminated_details' => 'required_if:is_tenant_terminated,yes',
            'is_tenant_refused' => 'required',
            'tenant_refused_details' => 'required_if:is_tenant_refused,yes',
            'is_on_debt' => 'required',
            'on_debt_details' => 'required_if:is_on_debt,yes',
            'is_deduction_rental_bond' => 'required',
            'deduction_rental_bond_details' => 'required_if:is_deduction_rental_bond,yes',
            'affect_future_rental_payment' => 'required',
            'affect_future_rental_payment_details' => 'required_if:affect_future_rental_payment,yes',
            'is_another_pending_application' => 'required',
            'own_a_property' => 'required',
            'own_a_property_details' => 'required_if:own_a_property,yes',
            'buy_another_property' => 'required',
            'intend_to_buy_after' => 'required_if:buy_another_property,yes',

            // Moving Service
            'need_moving_service' => 'required',
            'moving_service_agreement' => 'required',

            // Property Declaration
            'inspected_this_property' => 'required',
            'inspection_date' => 'required_if:inspected_this_property,yes',
            'good_condition' => 'required_if:inspected_this_property,yes',

            // Licence and aggreement
            'licence_and_agreement' => 'required',
        ]);

        $application = $this->save_application_form($request);

        $this->save_application_occupant($application->id);
        $this->save_application_children($application->id);
        $this->save_application_pet($application->id);
        $this->save_application_vehicle($application->id);
        $this->save_moving_service($application->id);

        $this->get_docusign_url($application->id);

        $application->update([
            'status' => '1',
            'draft' => '0'
        ]);

        $agency = Agency::whereName($application->agency_name)->first();

        if ($agency) {
            $setting_check = Setting::where('agency_id', $agency->id)->first();
            if ($setting_check && $setting_check->key == '1') {
                Mail::to($setting_check->value)->send(new MovingServiceMail($application->id));
            }
        }


        Mail::to(auth()->user()->email)->send(new NewApplicationSubmitted(auth()->user(), $application->id));
        Mail::to($application->property_manager_email)->send(new NewApplicationSubmittedForPropertyManager(auth()->user(), $application));

        flash('Application submitted successfully. Please Sign Your Document.')->success();
        return redirect('/sign-document/'.$application->id);
    }

    private function save_application_form($request)
    {
        $values = [
            // Property Details
            'applied_for' => $request->applied_for,
            'state' => $request->state,
            'suburb' => $request->suburb,
            'post_code' => $request->post_code,
            'property_type' => $request->property_type,
            'number_of_bedrooms' => $request->number_of_bedrooms,
            'commencement_date' => $request->commencement_date,
            'length_of_lease' => $request->length_of_lease,
            'weekly_rent' => $request->weekly_rent,
            'monthly_rent' => $request->monthly_rent,
            'bond' => $request->bond,
            'bond_assistance' => $request->bond_assistance,
            'property_found_in' => $request->property_found_in,

            // Property Manager Details
            'agency_name' => $request->agency_name,
            'property_manager_name' => $request->property_manager_name,
            'property_manager_email' => $request->property_manager_email,

            // Occupancy Details
            'number_of_occupant' => $request->number_of_occupant,
            'number_of_children' => $request->number_of_children,
            'number_of_vehicles' => $request->number_of_vehicles,
            'number_of_pets' => $request->number_of_pets,

            // Agent Specific
            'is_tenant_terminated' => $request->is_tenant_terminated,
            'tenant_terminated_details' => $request->tenant_terminated_details,
            'is_tenant_refused' => $request->is_tenant_refused,
            'tenant_refused_details' => $request->tenant_refused_details,
            'is_on_debt' => $request->is_on_debt,
            'on_debt_details' => $request->on_debt_details,
            'is_deduction_rental_bond' => $request->is_deduction_rental_bond,
            'deduction_rental_bond_details' => $request->deduction_rental_bond_details,
            'affect_future_rental_payment' => $request->affect_future_rental_payment,
            'affect_future_rental_payment_details' => $request->affect_future_rental_payment_details,
            'is_another_pending_application' => $request->is_another_pending_application,

app/Http/Controllers/UserDashboard/SignDocumentController.php
<?php

namespace App\Http\Controllers\UserDashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Tenant\TenantApplication;

class SignDocumentController extends Controller
{
    public function index($id)
    {
    	$url = TenantApplication::find($id)->docusign_url;
    	return view('user-dashboard.application.sign.index', compact('url'));
    }
}

resources/views/user-dashboard/includes/consultancy-status.blade.php
@if (!$valid_consultancy)
    <div class="alert alert-warning">
      <strong>Warning!</strong> {{ $message }}
    </div>
@endif

resources/views/user-dashboard/includes/header.blade.php
<div style="margin-top: 20px;"></div>
<style type="text/css">
    .vcenter{
        display: inline-block;
        vertical-align: middle;
        float: none;
    }
</style>
<div class="row text-center">
    <a href="{{ route('user-dashboard.applications.create') }}">
        <div class="col-md-4">
            <div class="panel panel-default top-panel {{ Request::is('applications/create') ? 'active' : '' }}">
                <div class="panel-body">
                    <div class="row">
                        <div class="vcenter">
                            <i class="fa fa-file"></i>
                            <h3>New Application</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>
    <a href="{{ route('user-dashboard.applications.index') }}">
        <div class="col-md-4">
            <div class="panel panel-default top-panel {{ Request::is('applications/*') && !Request::is('applications/create') || Request::is('applications') ? 'active' : '' }}">
                <div class="panel-body">
                    <div class="row" >
                        <div class="vcenter">
                            <i class="fa fa-eye"></i>
                            <h3>View Application</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>
    <a href="{{ route('user-dashboard.profile.index') }}">
        <div class="col-md-4">
            <div class="panel panel-default top-panel {{ Request::is('profile') ? 'active' : '' }}">
                <div class="panel-body">
                    <div class="row">
                        <div class="vcenter">
                            <i class="fa fa-user"></i>
                            <h3>Profile</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>
</div>

resources/views/user-dashboard/includes/nav.blade.php
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation" style="background: #FFF;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <a class="navbar-brand" href="/">
                    <img src="/images/logo-final.png" alt="Logo" height="39" style="margin-top: -10px;">
                    {{-- <span>Tenancy</span>
                    Application --}}
                </a>
                <ul class="nav navbar-top-links navbar-right tenancy-navbar">
                    @if (! $logged_in_user)
                    <li class="dropdown">
                        <a href="{{ route('frontend.auth.login') }}">Login</a>
                    </li>
                    <li class="dropdown">
                        <a href="{{ route('frontend.auth.register') }}">Register</a>
                    </li>
                    @else
                    <li class="dropdown">
                        <a class="ten-nav-btn" href="{{ route('frontend.user.dashboard') }}">
                            {{ trans('navs.frontend.dashboard') }}
                        </a>
                    </li>
                    <li class="dropdown" style="background: #fff;">
                        <a class="ten-welcome-user" href="#" data-toggle="dropdown" href="#">
                            Welcome <strong>{{ auth()->user()->name }}</strong>
                            <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            @if (Auth::user()->hasRole('property-manager'))
                                <li>{{ link_to_route('property-manager.dashboard', trans('navs.frontend.user.administration')) }}</li>
                            @endif

                            @if (Auth::user()->hasRole('administrator'))
                                <li>{{ link_to_route('admin.dashboard', trans('navs.frontend.user.administration')) }}</li>
                            @endif
                            
                            @if (Auth::user()->hasRole('agency-admin'))
                                <li>{{ link_to_route('agency.dashboard', trans('navs.frontend.user.administration')) }}</li>
                            @endif

                            {{-- <li>{{ link_to_route('frontend.user.account', trans('navs.frontend.user.account'), [], ['class' => active_class(Active::checkRoute('frontend.user.account')) ]) }}</li> --}}

                            <li>
                                <a href="/account">My Account</a>
                            </li>
                            
                            @if (Auth::user()->agency)
                                <li>{{ link_to_route('frontend.user.agency-details.create', trans('navs.frontend.user.agency'), [], ['class' => active_class(Active::checkRoute('frontend.user.agency-details.create')) ]) }}</li>
                            @endif
                            
                            <li>{{ link_to_route('frontend.auth.logout', trans('navs.general.logout')) }}</li>
                        </ul>

                    </li>
                    @endif
                </ul>
            </div>
        </div><!-- /.container-fluid -->
    </nav>